#!/bin/sh

# Folders
ROOT_DIR=".."
PKI_DIR="$ROOT_DIR/et-tdir1"
TLS_DIR="$PKI_DIR/easytls"

# Files
INLINE_CLI="$TLS_DIR/c08.inline"
OVPN_BIN="/home/tct/openvpn/master/src/openvpn/openvpn"

# Command line
OVPN_CMD=" \
--config $INLINE_CLI \
--verb 4 \
--remote 127.0.0.1 \
--proto udp \
--port 34571 \
--lport 12709 \
--dev tun12709 \
--connect-retry 2 5 \
--client \
--auth-user-pass userpass.1 \
--push-peer-info \
"
FULL_CMD="$OVPN_BIN $OVPN_CMD"

# Run the client
echo $FULL_CMD
# NOTE: Use of sudo - OpenVPN REQUIRES sudo
# There is no malicious code in these scripts
sudo $FULL_CMD

# NOTE: c08 will succeed
# Only run one client instance at a time
