#!/bin/sh

# Folders
ROOT_DIR=".."
PKI_DIR="$ROOT_DIR/et-tdir1"
TLS_DIR="$PKI_DIR/easytls"

# Files
INLINE_SRV="$TLS_DIR/s01.inline"
OVPN_BIN="openvpn"
DH_FILE="$ROOT_DIR/debug/dh.pem"

# Config
EASYTLS_CRYPT_V2_CONFIG="$ROOT_DIR/easytls-cryptv2-script.conf"
CRL_FILE="$PKI_DIR/crl.pem"

#EASYTLS_CRYPT_V2_VERIFY="$ROOT_DIR/easytls-cryptv2-verify.sh"
#EASYTLS_CRYPT_V2_VERIFY_CONF="$ROOT_DIR/debug/easytls-crypt-v2-verify.conf"
#EASYTLS_CRYPTV2_CLIENT_CONNECT="$ROOT_DIR/easytls-cryptv2-client-connect.sh"
#EASYTLS_CRYPTV2_CLIENT_CONNECT_CONF="$ROOT_DIR/debug/easytls-cryptv2-client-connect.conf"
#AUTH_USER_PASS_VERIFY="$ROOT_DIR/debug/auth-user-pass-verify.conf"
#PUSH_CONF="$ROOT_DIR/debug/push.conf"

# Command line
OVPN_CMD=" \
--config $INLINE_SRV \
--config $EASYTLS_CRYPT_V2_CONFIG \
--dh $DH_FILE \
--script-security 2 \
--crl-verify $CRL_FILE \
--verb 4 \
--local 127.0.0.1 \
--management 127.0.0.1 44571 \
--proto udp \
--port 34571 \
--dev tun34571 \
--server 10.127.121.0 255.255.255.240 \
--keepalive 5 30 \
--reneg-sec 300 \
"

FULL_CMD="$OVPN_BIN $OVPN_CMD"

# Run the server
echo $FULL_CMD
# NOTE: Use of sudo - OpenVPN REQUIRES sudo
# There is no malicious code in these scripts
sudo $FULL_CMD



